QA Python Sprint 4 final task
vkharnovets/Sprint_4 pull request #1
Opened 2023-05-21 20:54 UTC by vkharnovets

2023-05-23 16:43 UTC, kadirovgm requested changes

2023-05-23 16:43 UTC, kadirovgm commented on README.md
> +pip install -r requirements.txt
можно лучше: в readme стоит описать более подробную инфу о проекте, о тестах, о библиотеках и фреймворках, которые были использованы

2023-05-23 16:43 UTC, kadirovgm commented on conftest.py
Нужно исправить: необходимо добавить самую важную фикстуру, отвечающую за setup и teardown

Пример:

```
@pytest.fixture()
def driver():
    driver = webdriver.Chrome()
    driver.get(<url main page>)

    yield driver
    driver.quit()
```

Нужно минимизировать повторяющиеся строки кода, в твоих тестах teardown и setup методы описаны для каждого теста, для более лаконичности необходимо их вынести в [conftest.py](http://conftest.py/)

2023-05-23 16:43 UTC, kadirovgm commented on pages/base_page.py
> +    def load(self):
Можно лучше: лучше передать URL в аргументы функции, ведь мы должны стремиться к переиспользуемости методов

2023-05-23 16:43 UTC, kadirovgm commented on pages/base_page.py
> +
Все хорошо, но мало.

BasePage - это такой родительский класс, в котором содержатся общие методы, такие как: клик по определенному элементу, скролл к определенному элементу, ожидание определенного элемента, изменение табов итд.

То есть эти методы не привязаны к определенной странице, и могут быть переиспользованы в любой POM-странице, стоит сюда добавить именно такие методы.

2023-05-23 16:43 UTC, kadirovgm commented on urls.py
> +class Urls:
Отлично! молодец, что вынесла тестовые данные (ссылки в отдельный файл)

2023-05-23 16:43 UTC, kadirovgm commented on tests/test_home_page.py
> +        assert is_answer_visible is True
Нужно исправить: надо проверять не только то, что ответ существует, а также корректен ли он, то есть необходимо сравнить текст в ответе с ожиданием, иначе тест неполный

2023-05-23 16:43 UTC, kadirovgm commented on tests/test_home_page.py
> +        assert self.driver.current_url == Urls.order_page
Нужно исправить: проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-05-23 16:43 UTC, kadirovgm commented on tests/test_home_page.py
> +        assert self.driver.current_url == Urls.order_page
Нужно исправить: проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-05-23 16:43 UTC, kadirovgm commented on tests/test_order_page.py
> +            'name': 'Виктория',
Отлично! молодец, что пользуешься параметризацией

Можно лучше: я бы посоветовал вынести тестовые данные отдельно от тестов, по аналогии с классом Urls() можно создать класс Persons()

2023-05-23 16:43 UTC, kadirovgm commented on tests/test_order_page.py
> +        assert self.driver.current_url == Urls.dzen_page
Нужно исправить: проверка того, что URL поменялся на не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-05-23 16:43 UTC, kadirovgm commented on tests/test_order_page.py
> +        assert self.driver.current_url == Urls.home_page
Нужно исправить: проверка того, что URL поменялся на не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-05-24 12:27 UTC, vkharnovets commented on README.md
> +pip install -r requirements.txt
Сделано

2023-05-24 12:29 UTC, vkharnovets commented on conftest.py
Сделано. В уроках по POM был отдельный раздел про Setup и Teardown - у меня сложилось впечатление, что автопы курса хотели, чтобы инициализация тестовых классов была через них.

2023-05-24 12:38 UTC, vkharnovets commented on pages/base_page.py
> +    def load(self):
Сделано.
Пожалуй, это самый дискуссионный камент, на мой взгляд. Если сделать общий load, то нарушается инкапсуляция:

        home_page = HomePage(driver)
        home_page.load(Urls.order_page) #WTF?
        
В результате, сделан load(url) в базовом классе, как общая реализация, и load() в наследниках, вызывающие базовый load(url) c конкретным урлом - из тестов юзаются они. Еще остались вопросы с доступом к базовому методу - стоит закрывать, или нет.
В общем, не знаю, текущий варик выглядит поаккуратнее, чем было, пожалуй, но полного удовлетворения нет)

2023-05-24 12:39 UTC, vkharnovets commented on pages/base_page.py
> +
Сделано.
Идея понравилась - код тестов стал нагляднее.

2023-05-24 12:39 UTC, vkharnovets commented on tests/test_home_page.py
> +        assert is_answer_visible is True
Сделано

2023-05-24 12:39 UTC, vkharnovets commented on tests/test_home_page.py
> +        assert self.driver.current_url == Urls.order_page
Сделано

2023-05-24 12:39 UTC, vkharnovets commented on tests/test_home_page.py
> +        assert self.driver.current_url == Urls.order_page
Сделано

2023-05-24 12:41 UTC, vkharnovets commented on tests/test_order_page.py
> +            'name': 'Виктория',
Сделано.
Вынесено в отдельную папку test_data, заодно туда данные с вопросами положены в отдельным файле

2023-05-24 12:42 UTC, vkharnovets commented on tests/test_order_page.py
> +        assert self.driver.current_url == Urls.dzen_page
Сделано.

2023-05-24 12:43 UTC, vkharnovets commented on tests/test_order_page.py
> +        assert self.driver.current_url == Urls.home_page
Сделано

2023-05-24 21:50 UTC, kadirovgm requested changes

2023-05-24 21:50 UTC, kadirovgm commented on pages/base_page.py
> +    def load(self):
Нет, смотри, тебе нужно загрузить страницу, зачем ты это делаешь через объект класса страницы, например home_page.load(Urls.order_page), вместо этого перед началом теста достаточно вызвать базовый метод self.load(Urls.order_page)

2023-05-24 21:50 UTC, kadirovgm commented on README.md
> +pip install -r requirements.txt
отлично!

2023-05-24 21:50 UTC, kadirovgm commented on conftest.py
Кстати, можешь в эту фикстуру и вставить загрузку главной страницы, если ты хочешь все тесты начинать с главной, как у меня указано в примере

2023-05-24 21:50 UTC, kadirovgm commented on conftest.py
> +@pytest.fixture(scope="session")
Нужно исправить: не очень понял зачем `scope=session`? нам же нужно открывать бразуер и закрывать для каждого теста отдельно (по аналогии с твоим setup и teardown для каждого теста)

В данном случае нужен будет `scope=function` - это значение по умолчанию.

Смотри, фикстура должна заменять рутинные действия, такие как setup и teardown для каждорго теста и другие такие моменты, генерация тестовых данных например, или выбор нужного окружения

2023-05-24 21:50 UTC, kadirovgm commented on pages/base_page.py
Отлично!

2023-05-24 21:50 UTC, kadirovgm commented on pages/home_page.py
> +    def load(self):
Нужно исправить: это лишнее, можно просто пользоваться базовым методом

2023-05-24 21:50 UTC, kadirovgm commented on pages/order_page.py
> +    def load(self):
Нужно исрпвить: и тут

2023-05-24 21:50 UTC, kadirovgm commented on test_data/orders.py
> +class Orders:
Отлично! только скорее не Orders может, а Persons

2023-05-24 21:50 UTC, kadirovgm commented on test_data/questions.py
> +
Круто :)

2023-05-25 12:16 UTC, vkharnovets commented on test_data/orders.py
> +class Orders:
Может быть, это выгляит контринтуитивно, но это точно Order, а не Person. У Person не может быть поля Comment.
В большом проекте, возможно, был бы отдельный Person, а Order бы заполнялся на его основе, но, как по мне, в учебном проекте это явный перебор.

2023-05-25 12:27 UTC, vkharnovets commented on conftest.py
> +@pytest.fixture(scope="session")
Хм, предполагалось, что мы не будем переоткрывать браузер на каждый тест, а как раз будем открывать его один раз на набор тестов в классе, чтобы сэкономить время. Так не делают? Сколько же времени тогда будет выполняться прогон тестов...
Я поправлю, не вопрос, просто отмечаю, что это был осознанный выбор - то же самое поведение, что и в случае с setup_class/teardown_class

2023-05-25 12:30 UTC, vkharnovets commented on pages/home_page.py
> +    def load(self):
Сделано

2023-05-25 12:31 UTC, vkharnovets commented on pages/order_page.py
> +    def load(self):
Сделано

2023-05-25 13:31 UTC, vkharnovets commented on conftest.py
Да, так и сделаю, ИМХО это лучше, чем ломать копья о сигнатуру метода load()

2023-05-25 13:32 UTC, vkharnovets commented on pages/base_page.py
> +    def load(self):
Я не понимаю, как сделать self.load(Urls.order_page) перед началом теста - тест это же не POM-объект, а отдельный класс, он не наследуется от BasePage, так что там будет не self, а home_page
Если же написать внутри теста код в стиле
home_page.load(Urls.order_page),
то это провоцирует к тому, чтобы нарушить внутреннее состояние объекта, передав ему не тот адрес.

Я сделаю открытие главной страницы внутри fixture (это будет один раз на весь проект и вероятность ошибиться минимальна) и дальше переход на тестируемую страницу.

2023-05-26 20:01 UTC, kadirovgm commented on conftest.py
> +@pytest.fixture(scope="session")
В курсе предполагается, что для каждого теста должен запускаться браузер по новой, это позволит сказать что наши тесты точно не будут зависеть от состояния других. Но в целом твой вариант тоже можно использовать, тут уже смотря какую стратегию тестирования вы выбираете

2023-05-26 20:06 UTC, kadirovgm commented on pages/base_page.py
> +    def load(self):
Да, согласен, так будет лучше, тут я ошибся, посчитал, что это POM страница

2023-05-26 20:06 UTC, kadirovgm approved these changes

2023-05-26 20:27 UTC, merged